PART2: dict[str, dict] = {
    "abs": {
        "short": "Мост Abstract L2 — перевод активов между Ethereum и consumer L2 от экосистемы Pudgy Penguins.",
        "long": "Abs Bridge — официальный шлюз на Abstract, L2 с фокусом на consumer crypto и gaming. Депозит с Ethereum, вывод обратно через стандартную механику rollup-моста.",
        "tagline": "Вход в Abstract — мост, когда зовёт penguin L2.",
        "highlight": "Abstract — consumer L2 от Igloo Inc (Pudgy Penguins). Abs Bridge на bridge.abs.xyz — точка входа для ETH и поддерживаемых токенов с mainnet. Как у большинства optimistic/zk rollup, депозит быстрый, вывод может занимать часы или дни через challenge period. Экосистема растёт вокруг gaming и NFT — мост нужен, если ты уже в Ethereum и хочешь on-chain активность на Abstract без CEX.",
        "facts": [
            "Pivot Pudgy Penguins → Abstract L2 в 2024: NFT-коллекция стала L2-брендом — редкий случай, когда JPEG-команда строит инфраструктуру.",
            "Хайп consumer L2: TVL моста скачет в launch week и падает без sticky apps — Abstract борется за retention, а не только за airdrop farmers.",
            "Коллизия имён ABS: пользователи путали bridge.abs.xyz с другими «ABS» токенами — всегда проверяй контракт на официальном сайте.",
        ],
        "tips": ["Для крупных сумм делай тестовую tx — UI новых L2-мостов иногда показывает устаревшие адреса контрактов."],
        "warnings": ["Вывод с L2 на Ethereum не мгновенный — закладывай время challenge period, не последний день дедлайна."],
    },
    "across-bridge": {
        "short": "Быстрый optimistic bridge — переводы между L2 и L1 за минуты через сеть relayer.",
        "long": "Across — cross-chain bridge от Risk Labs с optimistic verification. Relayers авансируют капитал, пользователь получает средства быстро; disputing window защищает от мошенничества.",
        "tagline": "Мост за минуты, не дни — optimistic speed с ликвидностью relayer.",
        "highlight": "Across.to — один из самых быстрых мостов в DeFi: ETH и stablecoins между Ethereum, Arbitrum, Optimism, Base, Polygon и др. Модель: relayer даёт токены на destination сразу, потом протокол settle на origin. LP зарабатывают fees за ликвидность. Интегрирован в агрегаторы (Bungee и др.). Дешевле и быстрее canonical bridge для большинства сценариев, но trust assumptions отличаются от native rollup bridge.",
        "facts": [
            "Speed wars Across vs Hop vs Stargate в 2023: Across выигрывал на ETH-маршрутах по median time — маркетинг «2 minutes bridge» стал отраслевым бенчмарком.",
            "Optimistic oracle UMA лежит в core Across — один dispute может заморозить средства relayer; драма редкая, но архитектура не волшебная.",
            "Risk Labs привлекла $10M+ — мост пережил несколько медвежьих рынков без major exploit, редкость в bridge sector.",
        ],
        "tips": ["Сравни fee + estimated time с canonical bridge — для малых сумм Across почти всегда выигрывает."],
        "warnings": ["Риск моста остаётся: используй официальный UI across.to, не случайные клоны агрегаторов."],
    },
    "alcor": {
        "short": "Order book DEX на Antelope (EOS/WAX) — limit orders on-chain для тех, кто помнит EOS DeFi.",
        "long": "Alcor — децентрализованная биржа с CLOB-моделью на Antelope blockchain. Работает на WAX и других форках EOSIO — ниша, но с лояльным сообществом.",
        "tagline": "On-chain order book на Antelope — старая chain, настоящие limit orders.",
        "highlight": "Alcor.exchange — редкий зверь: полноценный order book DEX не на Ethereum. Limit и market orders on-chain на WAX/Antelope с низкими fees и быстрой финальностью. NFT и gaming tokens экосистемы WAX торгуются здесь. Ликвидность не сравнить с Uniswap, но для WAX-native assets — основная площадка. Cross-chain не core feature; это локальный DEX для локальной chain.",
        "facts": [
            "Золотой век EOS DeFi 2020: Alcor и Newdex делили order flow — потом Ethereum DeFi в 100 раз обогнал их объём, но WAX community осталась.",
            "Gaming NFT на WAX: миллионы micro-transactions — Alcor ловит trade flow от Alien Worlds и подобных, не whale DeFi.",
            "Rebrand Antelope от EOSIO: Alcor пережил chain politics, которые убили половину EOS dApps.",
        ],
        "tips": ["Для WAX tokens проверяй, что пара на Alcor — основная площадка ликвидности, а не side pool."],
        "warnings": ["Экосистема Antelope маленькая — exit liquidity на крупных позициях может быть проблемой."],
    },
    "allbridge": {
        "short": "Multi-chain bridge — переводы между EVM, Solana, Stellar и другими сетями через единый UI.",
        "long": "Allbridge — cross-chain bridge с поддержкой десятков сетей включая non-EVM. Native и wrapped token transfers, liquidity pools на destination.",
        "tagline": "Много chain — один мост, когда токены живут везде.",
        "highlight": "Allbridge.io соединяет Ethereum, BSC, Solana, Polygon, Avalanche, Near, Stellar и др. Модель pool-based: провайдеры ликвидности зарабатывают fees, пользователи свапают между chain. Поддержка SPL, ERC-20 и экзотических форматов. Полезен, когда нужен маршрут, которого нет у Celer или Stargate. История включает прошлые security incidents — сообщество следит за audits и upgrades.",
        "facts": [
            "Hack март 2023: Allbridge потерял ~$570K из BSC pool — протокол paused, часть средств recovered; bridge sector «ещё один» moment.",
            "Solana ↔ EVM через Allbridge был hot route до доминирования Wormhole и deBridge — speed vs trust tradeoff.",
            "Интеграция Stellar — редкий мост для XLM ecosystem в DeFi; ниша, но уникальная.",
        ],
        "tips": ["После любого bridge incident проверяй, какие pools restored — не все chains recover одинаково."],
        "warnings": ["Cross-chain bridges — top attack vector в DeFi; не гоняй через bridge больше, чем готов потерять."],
    },
    "altura": {
        "short": "Perp и spot trading — leveraged positions и markets для активных трейдеров.",
        "long": "Altura Trade — торговый интерфейс с perpetual и spot markets. Фокус на execution и leverage для пользователей, которым нужен terminal-style UX.",
        "tagline": "Торговля с leverage — perp terminal для активных дегенов.",
        "highlight": "Altura на app.altura.trade предлагает perpetual contracts и spot trading в едином интерфейсе. Leverage, funding rates и liquidation mechanics — стандартный perp playbook. Ликвидность и поддерживаемые markets зависят от underlying infrastructure — проверяй depth перед size. Для трейдеров, которым нужен альтернативный frontend к on-chain или hybrid perp liquidity.",
        "facts": [
            "Boom perp DEX 2024–2025: десятки новых terminals как Altura боролись за долю после того, как dYdX и Hyperliquid доказали размер рынка.",
            "Leverage tourism: трейдеры заходят на 20x, одна funding period — account rekt; Altura не исключение.",
            "app.altura.trade vs fake domains — perp terminals популярная цель для phishing; добавь official URL в закладки.",
        ],
        "tips": ["Funding rate и open interest смотри перед hold overnight — на alt perps может съесть PnL."],
        "warnings": ["Leveraged trading — риск ликвидации. Size position под volatility, а не под максимальный slider."],
    },
    "ambient": {
        "short": "Concentrated liquidity DEX на Ethereum — swap и LP с capital efficiency выше классического AMM.",
        "long": "Ambient Finance (ex-CrocSwap) — next-gen AMM с ambient liquidity model на Ethereum mainnet. Меньше capital для той же глубины, чем Uniswap v2.",
        "tagline": "Capital-efficient AMM — больше глубины на каждый доллар LP.",
        "highlight": "Ambient.finance переизобретает market making: ликвидность динамически концентрируется вокруг цены, fees копятся LP. Ребренд с CrocSwap после years of development — команда с серьёзным academic DeFi background. Mainnet Ethereum focus — gas matters, но для serious size efficiency wins. Swap UI straightforward; LP требует понимания range и impermanent loss mechanics.",
        "facts": [
            "Rebrand CrocSwap → Ambient 2023: years of stealth dev, community ждал «Uniswap killer» — realistic pitch скромнее, но tech solid.",
            "Ambient liquidity paper citations: academic DeFi редко доходит до mainnet; Ambient — exception с published research.",
            "Ethereum-only в multi-chain era: ставка на security и liquidity depth одной сети vs spray on every L2.",
        ],
        "tips": ["Для LP начни с narrow range на stable pairs — IL lower, mechanics понятнее."],
        "warnings": ["Concentrated liquidity = higher IL risk on volatile pairs при выходе price из range."],
    },
    "angle-bridge-by-l0": {
        "short": "Мост Angle Protocol через LayerZero — agEUR и assets между chains в экосистеме Angle.",
        "long": "Angle Bridge (LayerZero) — официальный cross-chain gateway для agEUR и Angle products. OFT standard LayerZero для token transfers между supported networks.",
        "tagline": "agEUR идёт cross-chain — LayerZero мост для экосистемы Angle.",
        "highlight": "Angle Money выпускает agEUR — overcollateralized Euro stablecoin. Мост через LayerZero позволяет держать и использовать agEUR на Arbitrum, Optimism, Polygon и др. без CEX. Интеграция с mint/redeem Angle и transmuter mechanics на destination. LayerZero messaging — быстро, но trust assumptions включают oracle/relayer set. Для Euro-denominated DeFi exposure без банковского счёта.",
        "facts": [
            "Angle пережил конкуренцию EURC от Circle — agEUR нишевый, но лояльные EU DeFi users остались.",
            "LayerZero airdrop farming 2023: txs через Angle bridge взлетели — половина sybil, половина реальный спрос на agEUR.",
            "Коллапс UST 2022: algorithmic stables умерли; overcollateralized модель Angle прошла stress test, когда другие — нет.",
        ],
        "tips": ["Mint agEUR на самой дешёвой chain, bridge если fee оправдан — не каждое направление симметрично по cost."],
        "warnings": ["Trust model LayerZero bridge отличается от canonical — читай docs перед крупными переводами."],
    },
    "arbitrum": {
        "short": "Ведущий Ethereum L2 — rollup с самой глубокой DeFi-экосистемой после mainnet, низкий gas и быстрые txs.",
        "long": "Arbitrum — optimistic rollup от Offchain Labs. Arbitrum One для general DeFi, Nova для gaming/low-cost. ARB token governance и grants для экосистемы.",
        "tagline": "Ethereum, но быстрее — L2, где реально живёт DeFi.",
        "highlight": "Arbitrum One — #1 L2 по TVL и DeFi activity: Uniswap, Aave, GMX, Camelot, Radiant — всё здесь. Nitro upgrade резко снизил fees. Sequencer centralized (пока), fraud proofs live. ARB airdrop 2023 — один из крупнейших retail airdrops в истории. Мост с Ethereum через official bridge или fast bridges (Across и др.). Developer ecosystem зрелая — если dApp на Ethereum, likely есть Arbitrum deploy.",
        "facts": [
            "ARB airdrop March 2023: ~625M tokens пользователям — median claim ~$1000+, у некоторых кошельков $50K+; определил эру «loyal L2 user».",
            "Arbitrum vs Optimism L2 wars: лидерство по TVL менялось, но Arbitrum держит top spot годами на raw DeFi usage, а не только на incentives.",
            "2024: Robinhood EU использовал Arbitrum для tokenized stocks — TradFi встретился с L2 быстрее, чем многие ожидали.",
        ],
        "tips": ["Для частых txs держи ETH на Arbitrum для gas — bridge batch, не каждый swap с mainnet."],
        "warnings": ["Вывод через official bridge на Ethereum — 7 дней challenge period; используй fast bridge при срочности."],
    },
    "arbswap": {
        "short": "Native DEX на Arbitrum — свапы и фарминг для локальных пар, когда не хочешь идти на Camelot.",
        "long": "Arbswap — AMM DEX на Arbitrum One с swap, liquidity pools и yield farming. Community-driven, меньше чем Camelot/Sushi на той же chain.",
        "tagline": "Нативный swap Arbitrum — локальный DEX для локальных дегенов.",
        "highlight": "Arbswap.io — mid-tier AMM на Arbitrum с classic pool model и farm incentives. Подходит для ecosystem tokens без deep liquidity на Uniswap. Fees ниже mainnet, но slippage на экзотических парах может быть высоким. Часть long tail Arbitrum DeFi — полезен для specific tokens, не default для ETH/USDC.",
        "facts": [
            "Фрагментация DEX на Arbitrum: Camelot, Sushi, Uniswap, Ramses, Arbswap — ликвидность размазана; пользователи гоняются за APR по всем.",
            "Дампы farm token: emissions Arbswap исторически следовали сценарию «launch high APR → TVL spike → token -90%».",
            "Малый DEX на большом L2: выживает на loyal community tokens, а не на объёме ETH/BTC.",
        ],
        "tips": ["Для major pairs используй Uniswap/Camelot; Arbswap — когда нужен specific ecosystem token."],
        "warnings": ["Farm APR в основном token emissions — считай реальный yield после падения цены farm token."],
    },
    "archly": {
        "short": "ve(3,3) DEX на multiple chains — swap, LP и vote-locked emissions в Solidly-style модели.",
        "long": "Archly Finance — AMM с ve-token governance на Base, Arbitrum, BSC и других. Bribe wars, gauge voting, concentrated liquidity variant.",
        "tagline": "ve(3,3) на твоей chain — голосуй за emissions, фарми со стратегией.",
        "highlight": "Archly.fi deploys Solidly-inspired mechanics: lock ARCH за veARCH, голосуй за pool emissions, LP зарабатывают trading fees + bribes. Multi-chain presence ловит рост локальных экосистем. Meta-game для DeFi strategists — bribe markets, vote optimization, dilution от новых pools. Не для новичков; награда за active management.",
        "facts": [
            "Solidly fork explosion 2022–2024: 100+ ve(3,3) DEX, 95% мертвы — Archly среди survivors на Base/Arbitrum.",
            "Bribe market drama: протоколы платят ve-holders за направление emissions — прозрачная коррупция, DeFi edition.",
            "ve-lock 4 года за max power: crypto years ощущаются как decades; большинство lockers не доходят до конца срока.",
        ],
        "tips": ["Перед LP проверь breakdown gauge APR — fees vs emissions vs bribes, а не headline number."],
        "warnings": ["ve-token locks длинные — early exit часто невозможен; не lock средства, которые нужны ликвидными."],
    },
    "arkm": {
        "short": "Arkham Intelligence — on-chain analytics и deanonymization labels, когда нужно знать, кто стоит за wallet.",
        "long": "Arkham — blockchain analytics platform с entity labels, wallet profiling и Intel Marketplace. ARKM token для platform access и rewards.",
        "tagline": "Чей это wallet? — on-chain intelligence для детективов.",
        "highlight": "Arkham.com агрегирует публичные chain data и применяет ML/heuristics для entity attribution — биржи, фонды, хакеры labeled. Intel Exchange позволяет покупать/продавать alpha о wallet identities. Controversial: privacy advocates ненавидят, трейдеры и compliance любят. Полезен для tracking smart money, hack fund flows, whale movements. Не trading venue — research tool.",
        "facts": [
            "Arkham doxxing drama 2023: платформа случайно слила planned dashboard раньше срока — паника crypto Twitter про «surveillance state».",
            "ARKM launch via Binance Launchpad — analytics token с immediate «sell the news» от airdrop hunters.",
            "Intel Marketplace: кто-то продал «кто этот hack wallet» за ETH — bounty hunter economy on-chain.",
        ],
        "tips": ["Cross-check labels Arkham с raw Etherscan — ML labels могут быть wrong или outdated."],
        "warnings": ["Entity attribution ≠ proof — false positives случаются; не обвиняй только по label."],
    },
    "arthswap": {
        "short": "Leading DEX на Astar Network — свапы и liquidity для Polkadot ecosystem parachain.",
        "long": "ArthSwap — primary AMM на Astar (Polkadot parachain) с multi-token pools и farm programs. Gateway для Substrate-ecosystem DeFi.",
        "tagline": "Домашний DEX Astar — свап в multi-chain backyard Polkadot.",
        "highlight": "ArthSwap на Astar Network обслуживает Polkadot-adjacent liquidity: DOT derivatives, ASTR, ecosystem tokens. Cross-chain через Polkadot XCM расширяет reach. Fees ниже, чем на Ethereum, TVL меньше, чем у top L2 DEX. Essential, если ты в экосистеме Astar; optional иначе.",
        "facts": [
            "Astar $22M+ raised от Polychain и других — победитель parachain auction нуждался в native DeFi; ArthSwap занял слот.",
            "Polkadot DeFi vs Ethereum: доля объёма меньше, но loyal builders; ArthSwap пережил bear, когда многие parachain dApps — нет.",
            "ASTR token incentives гнали TVL peaks — post-incentive retention всегда главный тест.",
        ],
        "tips": ["Bridge assets на Astar через official Polkadot routes перед swap — verify token contract."],
        "warnings": ["Parachain liquidity тоньше, чем на Ethereum L2 — size accordingly."],
    },
    "atomichub": {
        "short": "NFT marketplace на WAX — mint, buy и sell digital collectibles с zero gas fee UX.",
        "long": "AtomicHub — крупнейший NFT marketplace на WAX blockchain. Gaming items, collectibles, drops без Ethereum gas pain.",
        "tagline": "NFT без gas pain — WAX marketplace для gaming collectibles.",
        "highlight": "AtomicHub на wax.atomichub.io — NFT infrastructure для WAX: creators mint collections, users trade через WAX Cloud Wallet в пару кликов. Zero gas model через resource staking. Dominant venue для gaming NFTs (Alien Worlds и др.). Не fine art OpenSea — functional gaming assets и collectibles at scale.",
        "facts": [
            "WAX NFT volume peaked 2021–2022 с play-to-earn — AtomicHub обработал миллионы txs, когда Ethereum NFTs стоили $50 gas.",
            "AtomicAssets standard на WAX — template-based NFTs позволили game studios mint миллионы дёшево.",
            "P2E collapse: volume AtomicHub рухнул с ценами токенов — infrastructure осталась, hype — нет.",
        ],
        "tips": ["Verify collection creator перед покупкой — scam collections копируют popular game assets."],
        "warnings": ["Gaming NFTs часто illiquid — floor price ≠ exit price для твоего specific asset."],
    },
    "aurigami": {
        "short": "Lending protocol на Aurora (Near) — supply, borrow и yield на EVM-compatible Near L2.",
        "long": "Aurigami — money market на Aurora chain с algorithmic interest rates. Similar to Aave/Compound model в экосистеме Near.",
        "tagline": "Lend и borrow на Aurora — money market Near на EVM.",
        "highlight": "Aurigami Finance на Aurora предлагает supply/borrow для NEAR-wrapped и bridged assets. Aurora приносит EVM на Near — Aurigami native DeFi layer. Меньше Aave, но закрывает gap для Near community. Liquidation risks, utilization dynamics — standard lending playbook. Проверяй oracle sources и collateral factors.",
        "facts": [
            "Aurora launch as Near EVM: Aurigami среди первых lending protocols — first mover на small chain.",
            "Near ecosystem TVL never matched L2 stars — Aurigami quietly serves niche без headline hacks.",
            "2022 bear: Near-native protocols потеряли users на миграцию в Arbitrum — Aurigami удержал core Near believers.",
        ],
        "tips": ["Compare borrow APR across Aurora protocols — small ecosystem, rates могут diverge."],
        "warnings": ["Smaller lending markets = thinner liquidation liquidity — volatile collateral extra risky."],
    },
    "avalaunch": {
        "short": "Launchpad на Avalanche — IDO и продажи токенов для новых проектов экосистемы AVAX.",
        "long": "Avalaunch — децентрализованная fundraising platform на Avalanche. Stakers получают allocation в IDO через tier system.",
        "tagline": "IDO pad экосистемы AVAX — stake за allocation, ape responsibly.",
        "highlight": "Avalaunch.app проводит IDO для Avalanche-native projects: stake AVAX или platform token за tier, участвуй в sales, claim tokens на TGE. Реальность launchpad post-2021: большинство IDO underperform, gems единицы. Due diligence по fundamentals проекта обязателен. KYC иногда требуется в зависимости от sale.",
        "facts": [
            "Launchpad golden era 2021: sales Avalaunch sold out за секунды — average ROI positive тогда, negative сейчас.",
            "AVAX ATH $146 → launchpad hype correlated — tier stakers felt rich on paper, illiquid на cliff.",
            "Rug IDOs на каждой chain: Avalaunch delisted projects после community outrage — reputation management ongoing.",
        ],
        "tips": ["Читай vesting schedule перед IDO — liquid на TGE vs 12-month cliff меняет math полностью."],
        "warnings": ["IDO ≠ investment advice — majority launchpad tokens trend to zero; size as lottery ticket."],
    },
    "avalon-finance": {
        "short": "BTC-backed lending — залог Bitcoin, borrow stablecoins через CeDeFi и on-chain markets.",
        "long": "Avalon Finance — lending protocol с фокусом на Bitcoin collateral. Unlock BTC liquidity без продажи, multi-chain deployment.",
        "tagline": "Не продавай BTC — заложи его on-chain.",
        "highlight": "Avalon на app.avalonfinance.xyz позволяет Bitcoin holders deposit BTC (wrapped/native forms) и borrow stablecoins. Targets use case «HODL but need liquidity». CeDeFi elements возможны в зависимости от product line — verify custody model. LTV, liquidation thresholds и oracle pricing для BTC critical to monitor.",
        "facts": [
            "BTC DeFi lending вырос post-2024 ETF era — holders wanted yield и liquidity без tax event от продажи.",
            "Every BTC lending protocol faces same question: who holds keys? Avalon marketing emphasizes transparency — verify on-chain.",
            "Liquidation cascades на BTC collateral hurt harder — correlated dumps across all BTC-backed protocols simultaneously.",
        ],
        "tips": ["Conservative LTV на BTC — 50% safer than max allowed; volatility still bites «safe» collateral."],
        "warnings": ["BTC wrapper и custody model varies — understand what you deposit перед large amounts."],
    },
    "avnu": {
        "short": "DEX aggregator на Starknet — лучший маршрут свапа через AMMs в одной транзакции.",
        "long": "Avnu — smart order routing на Starknet, splitting trades across JediSwap, 10kSwap, SithSwap и др. за best price.",
        "tagline": "Лучший маршрут свапа на Starknet — один клик, много пулов.",
        "highlight": "Avnu.fi агрегирует Starknet DEX liquidity — user gets optimal price без manually checking each venue. Similar to 1inch на Ethereum. Supports limit orders и expanding advanced features. Essential tool по мере роста Starknet DEX fragmentation. Gas paid in STRK/ETH на Starknet.",
        "facts": [
            "Every L2 eventually gets aggregator — Avnu стал Starknet's 1inch за months of ecosystem maturity.",
            "Aggregator volume exceeds individual DEX during airdrop seasons — routing txs spike с STRK campaigns.",
            "Split routing saved users single-digit % на large swaps — adds up на whale size, invisible на $10 trades.",
        ],
        "tips": ["Slippage tolerance: 0.5% usually enough на Starknet; volatile tokens need 1%+."],
        "warnings": ["Aggregator adds smart contract layer — use official app.avnu.fi, verify URL."],
    },
    "axiom": {
        "short": "Pro trading terminal на Solana — perps, spot и analytics в одном UI для speed traders.",
        "long": "Axiom.trade — advanced trading interface для Solana ecosystem: fast execution, perp access, wallet tracking. Popular among memecoin и perp traders.",
        "tagline": "Speed trading Solana — terminal для clicks per second.",
        "highlight": "Axiom агрегирует Solana trading workflows: connect wallet, trade tokens и perps с minimal latency UI. Charting, order flow и social features target active traders, не long-term holders. Solana meme season drove adoption — speed matters когда token moves 50% за minutes. Not a DEX itself — frontend и routing layer.",
        "facts": [
            "Solana meme mania 2024–2025: terminals like Axiom, Photon, BullX competed — UX war as fierce as chain TPS war.",
            "Copy trading на Solana: follow wallet, auto-buy — made millionaires и victims same week.",
            "axiom.trade phishing clones rampant during SOL peaks — bookmark official domain.",
        ],
        "tips": ["Set slippage и priority fee перед FOMO click — Solana congested = failed or sandwiched txs."],
        "warnings": ["Memecoin trading is gambling — terminal speed doesn't fix 99% loss rate на random tokens."],
    },
    "base-name-service": {
        "short": "ENS на Base — human-readable .base names для wallet и on-chain identity.",
        "long": "Base Name Service (Basenames) — naming protocol на Base L2 от Coinbase ecosystem. Register username.base linked to address.",
        "tagline": "Yourname.base — identity на L2 от Coinbase.",
        "highlight": "Basenames на basename.app — on-chain names на Base: send to «alice.base» instead of 0x… Integrates с Coinbase Wallet и Base ecosystem apps. Cheaper registration than ENS на mainnet. Identity layer для social и payment use cases на Base. Resolvers, subdomains и renewals follow ENS-like model.",
        "facts": [
            "Coinbase pushed Basenames hard at Base launch — free/discounted names drove millions of registrations.",
            "ENS vs Basenames: two namespaces, potential confusion — alice.eth ≠ alice.base.",
            "Onchain Summer 2023: basename became flex PFP equivalent для Base builders.",
        ],
        "tips": ["Register primary name перед тем как someone squats your brand — cheap insurance."],
        "warnings": ["Names expire if not renewed — set reminder like domain registration."],
    },
    "bastion-protocol": {
        "short": "Lending на Aurora/Near — algorithmic rates для supply и borrow в Near EVM ecosystem.",
        "long": "Bastion Protocol — money market на Aurora с cToken model similar to Compound. Near-native DeFi lending option.",
        "tagline": "Compound vibes на Aurora — lending экосистемы Near.",
        "highlight": "Bastion на Aurora offers supply/borrow markets для bridged assets на Near's EVM layer. Interest rates algorithmic based on utilization. Competes с Aurigami за same user base. Smaller TVL, higher relative risk на exotic collateral. Historical Near ecosystem protocol — survived multiple market cycles на niche chain.",
        "facts": [
            "Near + Aurora dual branding confused users for years — Bastion на Aurora, not Near L1 directly.",
            "2022 Terra collapse: algorithmic stable borrowers на all lending protocols rekt — Bastion had minimal UST exposure.",
            "Bastion vs Aurigami на same chain — liquidity split hurts both; classic small ecosystem problem.",
        ],
        "tips": ["Check utilization на borrow asset — high utilization spikes borrow APR fast."],
        "warnings": ["Niche chain lending — exit liquidity и oracle reliability lower than Ethereum blue chips."],
    },
    "bebop": {
        "short": "Professional DEX aggregator — RFQ и aggregated liquidity для size trades с minimal slippage.",
        "long": "Bebop — liquidity aggregator targeting professional и semi-pro traders. Request-for-quote model alongside AMM aggregation для better execution на size.",
        "tagline": "Размер имеет значение — RFQ aggregation для тех, кто двигает рынок.",
        "highlight": "Bebop.xyz routes large swaps через market maker quotes и DEX liquidity — minimizes price impact vs single-pool AMM. Supports multiple chains и pairs. PMM и RFQ hybrid reduces MEV exposure для takers. Built для traders frustrated с Uniswap slippage на $100K+ trades. Gas и approval flow optimized для repeat users.",
        "facts": [
            "RFQ models gained share post-MEV awareness — Bebop rode «private market maker fills your trade» narrative.",
            "Wintermute и other MMs integrate с Bebop — institutional liquidity retail can access.",
            "Aggregator wars: 1inch, Matcha, Bebop, CowSwap — each claims best execution; truth is pair-dependent.",
        ],
        "tips": ["Compare Bebop quote с CowSwap и 1inch на same trade — best venue changes by pair и size."],
        "warnings": ["RFQ quotes expire — confirm quickly or refresh before sign."],
    },
    "beefy-finance": {
        "short": "Yield optimizer — auto-compound vaults across chains, когда не хочешь вручную harvest каждый день.",
        "long": "Beefy Finance — multi-chain yield aggregator. Депозит LP или single assets, vault auto-compounds награды в больший yield.",
        "tagline": "Поставил vault — забыл harvest — auto-compound на 30+ chain.",
        "highlight": "Beefy.finance разворачивает vault-стратегии на BSC, Ethereum, Arbitrum, Polygon, Fantom и десятках других сетей. Принимает LP-токены или активы, фармит награды, продаёт и реинвестирует автоматически — экономит gas и время по сравнению с ручным compound. Токен BIFI даёт долю revenue. Стратегии различаются по риску: stable pools безопаснее, degen farms — выше APY и выше rug risk. Всегда читай strategy contract и underlying protocol.",
        "facts": [
            "Beefy пережил медвежий 2022, когда многие yield aggregators умерли — мем «billion dollar compounding» стал брендом доверия.",
            "Vault hack 2021 на старой стратегии — Beefy компенсировала и ужесточила approval process; playbook прозрачности.",
            "Multi-chain vault count 1000+: вручную не аудируешь все — держись blue chip underlying pools.",
        ],
        "tips": ["Предпочитай vaults с audited underlying (Curve, Uniswap) экзотическим single-audit farms."],
        "warnings": ["Auto-compound ≠ safe — vault strategy может потерять, если underlying farm rug или exploit."],
    },
    "benqi": {
        "short": "Core lending и liquid staking на Avalanche — QI markets plus sAVAX для staking liquidity.",
        "long": "Benqi — ведущий Avalanche DeFi: money markets для supply/borrow и sAVAX liquid staking token. Опора экосистемы AVAX.",
        "tagline": "Опора DeFi Avalanche — lend, borrow, stake без lock AVAX.",
        "highlight": "Benqi.fi ведёт supply/borrow markets (QI) и liquid staking (sAVAX) на Avalanche C-Chain. sAVAX представляет застейканный AVAX, пригодный в DeFi — composability win. Глубокая интеграция с Avalanche DeFi stack. Механика ликвидации стандартная; волатильность AVAX движет collateral risk. Native AVAX yield + DeFi leverage в одной точке экосистемы.",
        "facts": [
            "Benqi годами доминировал в Avalanche lending TVL — неофициальное звание «Aave of AVAX».",
            "AVAX -90% от ATH stress-tested ликвидации Benqi — протокол выстоял, часть пользователей — нет.",
            "sAVAX depeg scare во время хаоса FTX — восстановился; момент доверия к LST для Avalanche.",
        ],
        "tips": ["sAVAX полезен как DeFi collateral; сравни borrow rate vs staking yield перед leverage loop."],
        "warnings": ["Depeg liquid staking token в панике рынка — не считай 1:1 AVAX гарантией всегда."],
    },
}
