PART3: dict[str, dict] = {
    "bitcow": {
        "short": "MEV-aware trading на Bitcoin L2 — свапы с защитой от sandwich на emerging BTC DeFi.",
        "long": "BitCow — DEX/trading на Bitcoin Layer 2 с фокусом на честное исполнение и MEV mitigation для BTC trades.",
        "tagline": "Честные свапы на Bitcoin L2 — меньше sandwich, больше satoshis.",
        "highlight": "BitCow.xyz работает в пространстве Bitcoin L2 DeFi: свапы и ликвидность, пока BTC-экосистема расширяется за пределы store of value. Нарратив MEV protection похож на CowSwap на Ethereum. Инфраструктура BTC DeFi на ранней стадии — ликвидность растёт, но тоньше, чем на Ethereum. Для пионеров, исследующих programmable money на Bitcoin.",
        "facts": [
            "Bitcoin DeFi renaissance 2024–2025: Ordinals, Runes, L2 — BitCow среди инструментов, ловящих волну.",
            "BTC maxis vs DeFi degens — вечный спор; BitCow обслуживает меньшинство, которому нужно и то, и другое.",
            "Каждый новый BTC L2 заявляет «native Bitcoin DeFi» — большинство ликвидности всё ещё экспериментальное.",
        ],
        "tips": ["Начни с малых сумм — BTC L2 bridges и DEX liquidity ещё созревают."],
        "warnings": ["Модели безопасности BTC L2 сильно различаются — разберись с мостом перед депозитом."],
    },
    "bitgenie": {
        "short": "Bitcoin ecosystem platform — tools и markets на стыке BTC и DeFi utility.",
        "long": "BitGenie — платформа в Bitcoin DeFi/inscriptions space с trading, tools или launchpad features в зависимости от фазы продукта.",
        "tagline": "Bitcoin utility play — когда BTC нужен не только HODL.",
        "highlight": "BitGenie.io участвует в расширении Bitcoin-экосистемы за пределы простых переводов — inscriptions, swaps и ecosystem tools по мере эволюции рынка. Сектор движется быстро; продуктовая поверхность меняется с BTC L2 и meta trends. Для пользователей на Bitcoin DeFi frontier, исследующих новые интерфейсы.",
        "facts": [
            "Ordinals explosion породил десятки Bit* брендов — BitGenie среди имён, борющихся за Bitcoin DeFi mindshare.",
            "Inscription summer 2023: платформы взлетали и падали с floor prices — инфраструктура пережила hype cycles.",
            "Bitcoin DeFi UX всё ещё clunky vs Solana one-click — BitGenie и peers закрывают gap.",
        ],
        "tips": ["Проверь, какой Bitcoin L2 или layer использует BitGenie — совместимость с кошельком критична."],
        "warnings": ["Ранний BTC DeFi — smart contract и bridge risk выше, чем у зрелых Ethereum протоколов."],
    },
    "bitstar": {
        "short": "Trading и DeFi platform — swap и earn products для retail crypto users.",
        "long": "BitStar — multi-feature crypto platform с swap, earn и возможными launchpad elements на bitstar.pro.",
        "tagline": "Swap и earn hub — retail DeFi в одном dashboard.",
        "highlight": "BitStar.pro предлагает консолидированные DeFi-ish сервисы: token swaps, yield products и promotional campaigns. Mid-tier platform без tier-1 audit brand — due diligence по каждому продукту отдельно. Полезен как aggregator entry, если ecosystem matches твоим chains и tokens.",
        "facts": [
            "Bit* naming crowded в crypto — BitStar часто путают с unrelated projects; проверяй domain bitstar.pro.",
            "Retail DeFi platforms взлетают на bull и затихают на bear — TVL говорит правду.",
            "Promotional APR campaigns: читай fine print про lock period и withdrawal fees.",
        ],
        "tips": ["Earn products — отдельный risk от swap; разные contracts, разные audits."],
        "warnings": ["Non-blue-chip platforms — не депозить больше, чем готов потерять полностью."],
    },
    "bloctoswap": {
        "short": "DEX на Flow blockchain — свапы для Flow NFT и token ecosystem с Blocto wallet UX.",
        "long": "BloctoSwap — AMM на Flow с интеграцией Blocto wallet. Низкий friction для Flow-native users и NBA Top Shot adjacent ecosystem.",
        "tagline": "Дружелюбный DEX Flow — свап через Blocto wallet в пару тапов.",
        "highlight": "BloctoSwap на swap.blocto.app обслуживает Flow blockchain — Cadence smart contracts, consumer-friendly onboarding через Blocto. Ликвидность для FLOW и ecosystem tokens. Не deep DeFi — доступные свапы для Flow community и NFT collectors, выводящих активы in/out.",
        "facts": [
            "Flow позиционировался как consumer chain — BloctoSwap matched UX для non-crypto-native Top Shot users.",
            "Layoffs Dapper Labs и pivot Flow: ecosystem сжался, но core DEX продолжил обслуживать loyal base.",
            "Flow DeFi TVL never exploded — BloctoSwap остаётся modest, functional, niche.",
        ],
        "tips": ["Blocto wallet — smoothest Flow DEX experience; wallet fragmentation hurts на Flow."],
        "warnings": ["Thin pools на Flow — проверяй liquidity перед крупными swaps."],
    },
    "bluemove": {
        "short": "Leading DEX на Sui и Aptos — Move-language chains native AMM с concentrated liquidity.",
        "long": "BlueMove — primary DEX на Sui и Aptos Move VM chains. Swap, LP, launchpad features по мере роста ecosystem.",
        "tagline": "DEX Move chain — ликвидность Sui и Aptos в одном бренде.",
        "highlight": "BlueMove.net развёрнут на Sui и Aptos — ставка на Move language ecosystem независимо от того, какая L1 победит. Swap и liquidity pools для native tokens; historically strong during airdrop и incentive seasons. Multi-chain brand снижает single-chain risk. Конкуренция Cetus на Sui и других давит на fees и incentives.",
        "facts": [
            "Sui mainnet launch 2023: BlueMove day-one DEX — first mover advantage в gold rush новой L1.",
            "Move VM chains compete: Sui vs Aptos — BlueMove hedged обе в отличие от chain-maximalist DEX.",
            "Incentive farming на new L1s: BlueMove TVL correlated с token emission schedule, не organic volume.",
        ],
        "tips": ["Same brand, different chains — проверь correct network перед connect wallet."],
        "warnings": ["New L1 DEX liquidity volatile — IL и rug risk на fresh token pairs."],
    },
    "blur": {
        "short": "Pro NFT marketplace — zero fees для traders, bidding и analytics для serious flippers.",
        "long": "Blur.io — NFT marketplace для professional traders: aggregation, portfolio tools, zero marketplace fees, BLUR token incentives.",
        "tagline": "NFT trading terminal — нулевые fees, максимальная скорость, pro tools.",
        "highlight": "Blur потряс OpenSea trader-first design: floor sweeps, portfolio views, debates про royalty enforcement и эра BLUR airdrop farming. Aggregates listings across marketplaces. Lending (Blend) integrated для NFT-backed loans. Ethereum NFT focus — не multi-chain general marketplace. Controversial among creators за royalty stance; beloved flippers за economics.",
        "facts": [
            "Blur airdrop Season 1–2 распределил сотни миллионов BLUR — defined 2023 NFT trader behavior.",
            "OpenSea vs Blur market share war: Blur took #1 volume weeks running — first real OpenSea challenger.",
            "Blend NFT lending: borrow ETH against Punk или Azuki — liquidation auctions стали spectator sport.",
        ],
        "tips": ["Проверь royalty и marketplace fee по коллекции перед list — Blur rules differ от OpenSea."],
        "warnings": ["NFT lending liquidation — floor drop может уничтожить collateral value; borrow conservatively."],
    },
    "bulk": {
        "short": "Trading terminal — aggregated execution и tools для active on-chain traders.",
        "long": "Bulk.trade — professional trading interface с fast routing, analytics и workflow tools для DeFi traders.",
        "tagline": "Торгуй bulk — terminal speed для on-chain size.",
        "highlight": "Bulk даёт unified trading UX across supported chains и venues — minimizing tab switching для active traders. Charting, order execution и portfolio views target users, которым тесно в basic swap UI. Part of growing category DeFi terminals, конкурирующих на latency и feature depth.",
        "facts": [
            "Terminal wars 2024: dozens «fastest swap UI» — Bulk among names targeting pro segment, не retail.",
            "Aggregator backend matters less than frontend speed, когда memecoins move 100%/hour.",
            "Phishing clones follow every popular terminal — verify bulk.trade SSL и bookmarks.",
        ],
        "tips": ["Test с small trade first на new terminal — confirm routing и slippage behavior."],
        "warnings": ["Terminal — frontend only; underlying DEX и chain risks unchanged."],
    },
    "bungee": {
        "short": "Bridge aggregator от Socket — один UI для лучшего cross-chain маршрута и fee.",
        "long": "Bungee.exchange — aggregates bridges (Across, Stargate, Hop и др.) для optimal cross-chain transfer по time и cost.",
        "tagline": "Один bridge UI для всех — агрегация Socket.",
        "highlight": "Bungee от Socket.tech сравнивает routes across major bridges: different paths, fees и ETA shown transparently. User picks или auto-selects best. Refuel feature sends gas token на destination chain — решает боль «bridged USDC but no ETH for gas». Essential tool для multi-chain DeFi users, уставших проверять пять bridge sites.",
        "facts": [
            "Socket powered половину DeFi aggregator integrations — Bungee consumer face того же routing engine.",
            "Refuel feature saved millions «stuck on new chain» support tickets across crypto Twitter.",
            "Bridge aggregator не убирает bridge risk — just picks which protocol to trust this time.",
        ],
        "tips": ["Enable refuel с small native amount на first bridge to new chain — prevents stuck funds."],
        "warnings": ["Aggregators route through third-party bridges — each has own trust assumptions."],
    },
    "bunnyfi": {
        "short": "Yield farming platform — auto-compound и vault strategies на supported chains.",
        "long": "Bunnyfi — yield optimizer с vault products, auto-harvesting и reinvesting farm rewards.",
        "tagline": "Фарми без ежедневного harvest — Bunny делает compound.",
        "highlight": "Bunnyfi.io предлагает yield vaults категории Beefy — депозит, стратегия compound награды. Меньший footprint; проверяй audits и underlying protocols перед депозитом. APR headlines driven by token emissions — real yield often lower.",
        "facts": [
            "Yield aggregator sector crowded post-2020 — Bunnyfi among long tail competing for same farm tokens.",
            "Auto-compound saves gas for small farmers — economics matter only above certain deposit size.",
            "Farm token -95% destroys compounded gains — math cruel на high APR vaults.",
        ],
        "tips": ["Check underlying farm protocol audit status перед Bunny vault deposit."],
        "warnings": ["Optimizer adds smart contract layer on top of farm — stacked risk."],
    },
    "cashmere": {
        "short": "Stable swap bridge — optimized для USDC/USDT transfers между chains с minimal slippage.",
        "long": "Cashmere — cross-chain bridge с фокусом на stablecoin transfers, low slippage и competitive fees via optimized routing.",
        "tagline": "Stablecoins cross chains smoothly — minimal depeg on bridge.",
        "highlight": "Cashmere.exchange решает stablecoin bridge pain: крупные USDC moves между Ethereum, Arbitrum, Base и др. с tight peg и clear fees. Stable-focused design снижает volatility during bridge vs bridge volatile tokens. Полезен для moving dry powder между chains под opportunities.",
        "facts": [
            "Stablecoin bridge competition fierce — Cashmere vs Across vs Stargate на USDC routes.",
            "USDC circle CCTP changed bridge landscape 2023 — native burn/mint safer than liquidity pool bridges.",
            "Bridge slippage на stables should be ~0 — if not, something wrong с pool liquidity.",
        ],
        "tips": ["For large stables compare Cashmere quote с CCTP-native bridges на supported routes."],
        "warnings": ["Always verify receiving USDC contract address на destination — fake stables exist."],
    },
    "celer-cbridge": {
        "short": "Celer cBridge — established cross-chain bridge с liquidity pools и wide chain support.",
        "long": "cBridge от Celer Network — pool-based bridge connecting 40+ chains. Fast transfers, liquidity provider yields, deep integrations.",
        "tagline": "40+ chain connected — OG liquidity bridge всё ещё роутит.",
        "highlight": "cBridge.celer.network — veteran cross-chain bridge: deposit на source, LP pool pays destination. Supports EVM, Cosmos и more. Integrated в many wallets и dApps. History of security upgrades after 2022 incident — protocol improved monitoring. LP earns fees; users get speed vs canonical bridge.",
        "facts": [
            "August 2022 cBridge hack: ~$240K exploited, quick pause and fix — smaller than Ronin but wake-up call.",
            "Celer founded by PhD team from UIUC — academic cred rare among bridge teams.",
            "cBridge volume peaks during chain launches — everyone bridge to farm new airdrop.",
        ],
        "tips": ["Check transfer limits и estimated time in UI — large transfers may hit pool caps."],
        "warnings": ["Pool-based bridges have liquidity constraints — max transfer depends on destination pool depth."],
    },
    "cetus": {
        "short": "Top DEX на Sui — concentrated liquidity AMM, ecosystem hub для Move DeFi.",
        "long": "Cetus Protocol — leading DEX на Sui с CLMM model, deep integrations и CETUS token incentives.",
        "tagline": "Центр ликвидности Sui — CLMM для экосистемы Move.",
        "highlight": "Cetus.zone доминирует Sui DEX volume: concentrated liquidity pools, swap aggregator integration, launchpad support. Official-ish status в Sui ecosystem grants и partnerships. CETUS incentives drive LP; post-airdrop retention key metric. Essential venue для any Sui DeFi user.",
        "facts": [
            "Cetus mainnet day one with Sui — captured majority DEX share while BlueMove split Aptos focus.",
            "Sui Foundation backed ecosystem DEX narrative — Cetus benefited from grants и co-marketing.",
            "CLMM на new L1: LPs learned concentrated liquidity painful lesson from Uniswap v3 again.",
        ],
        "tips": ["For Sui swaps default to Cetus aggregator view — checks internal pools first."],
        "warnings": ["New ecosystem tokens extremely volatile — IL на concentrated ranges hurts fast."],
    },
    "chainspot": {
        "short": "Cross-chain swap hub — exchange tokens между networks через aggregated liquidity.",
        "long": "Chainspot — platform для cross-chain token swaps, combining bridge и DEX routing в unified flow.",
        "tagline": "Swap across chains — один flow от token A на chain X до B на chain Y.",
        "highlight": "Chainspot.io упрощает multi-hop trades: user specifies source chain/token и destination — backend routes bridge + swap. Reduces manual steps vs bridge then swap separately. Fee и time estimates upfront. Useful для opportunistic cross-chain arb и portfolio rebalancing.",
        "facts": [
            "Cross-chain swap UX improved 2023–2025 — Chainspot among interfaces hiding bridge+DEX complexity.",
            "Every aggregator faces same pain: one broken hop fails entire route — customer support nightmare.",
            "Chainspot volume correlates с alt season — quiet когда everyone stays on one chain.",
        ],
        "tips": ["Allow slippage buffer на cross-chain swaps — two hops compound price uncertainty."],
        "warnings": ["Multi-hop trades increase failure points — start with moderate size."],
    },
    "claimswap": {
        "short": "DEX на Klaytn — свапы и liquidity для Kakao-backed Korean blockchain ecosystem.",
        "long": "ClaimSwap — AMM на Klaytn (Kaia) serving Korean Web3 ecosystem tokens и KLAY pairs.",
        "tagline": "Swap desk Klaytn — ликвидность корейской экосистемы.",
        "highlight": "ClaimSwap.org работает на Klaytn/Kaia chain — enterprise-linked Korean blockchain с local gaming и payment integrations. Primary DEX для on-chain swaps, когда ты в Klaytn ecosystem. Volume tied to Korean market activity и ecosystem token launches.",
        "facts": [
            "Klaytn from Kakao/Ground X — ClaimSwap benefited from Korean corporate blockchain push.",
            "Kaia rebrand merger 2024: Klaytn + Finschia — ClaimSwap adapted to unified chain branding.",
            "Korean crypto regulation swings affect Klaytn activity — geography-specific risk factor.",
        ],
        "tips": ["Verify token is official Klaytn deployment — scam tokens common на regional chains."],
        "warnings": ["Regional chain liquidity limited — large trades move price significantly."],
    },
    "coinlist": {
        "short": "Token launch platform — compliance-heavy sales для early access к топ проектам до биржи.",
        "long": "CoinList.co — regulated token sale platform hosting Solana, Filecoin, Oceans и other historic launches. KYC required, lottery or auction formats.",
        "tagline": "Ранние токены до CEX — KYC, lottery, надежда.",
        "highlight": "CoinList проводил some of most famous token sales: Solana at $0.04, Flow, Mina и dozens more. Compliance-first approach vs pure crypto degen launchpads. Sales often lottery из-за oversubscription. Post-sale tokens vest or unlock on schedule. Reputation: legitimate platform, but returns vary wildly by project и entry price.",
        "facts": [
            "Solana CoinList sale 2020: $0.04 per SOL — best ROI in platform history, created permanent FOMO for every future sale.",
            "CoinList Mini и Karma system — farming reputation for allocation became part-time job for launch hunters.",
            "Not immune to bad sales: projects that listed strong still dumped 80% — platform legit ≠ token profit.",
        ],
        "tips": ["Read unlock schedule before sale — liquid at listing vs 12-month vest changes exit strategy."],
        "warnings": ["Token sales are high risk — past Solana returns won't repeat; most sales underperform."],
    },
    "cometbridge": {
        "short": "Cross-chain bridge — transfer assets между supported networks через Comet liquidity protocol.",
        "long": "CometBridge — bridge interface на cometbridge.app routing cross-chain transfers for ecosystem tokens и stables.",
        "tagline": "Мост под кометой — cross-chain, когда звёзды сходятся.",
        "highlight": "CometBridge provides cross-chain transfer UI connecting supported L1/L2 networks. Part of long tail bridge market — verify security audits, supported routes и liquidity before large transfers. Useful когда specific token or chain route not covered by major aggregators.",
        "facts": [
            "Bridge proliferation 2023–2024: hundreds of interfaces, dozen secure backends — Comet among niche routers.",
            "New bridge UIs spike usage during airdrop campaigns — sustainability depends on repeat users.",
            "Always compare with Bungee/Across before using unknown bridge — fee и safety tradeoff.",
        ],
        "tips": ["Test bridge with minimum amount on new route before moving size."],
        "warnings": ["Lesser-known bridges carry higher smart contract и liquidity risk — DYOR."],
    },
    "compound": {
        "short": "OG DeFi lending — algorithmic rates, cTokens и governance через COMP since 2018.",
        "long": "Compound Finance — pioneer algorithmic money market на Ethereum. Supply earns interest, borrow against collateral, COMP rewards for early users.",
        "tagline": "OG DeFi lending — где cTokens и liquidity mining начались.",
        "highlight": "Compound invented modern DeFi lending UX: deposit ETH → receive cETH → earn APR; borrow against it. COMP liquidity mining June 2020 kicked off DeFi Summer. v3 focuses on efficiency и isolation. Less multi-chain than Aave but Ethereum mainnet institutionally recognized. Governance via COMP holders — proposal drama frequent.",
        "facts": [
            "COMP yield farming June 2020: TVL 0 → $1B in weeks — invented liquidity mining, changed crypto forever.",
            "Compound Treasury proposal 2021: attempted corporate structure for protocol — legal innovation ahead of DAO law.",
            "2021 bug: $80M at risk, whitehat saved funds — Compound compensated generously; responsible disclosure win.",
        ],
        "tips": ["Mainnet gas makes Compound best for larger positions — small deposits eat yield on gas."],
        "warnings": ["Governance can change collateral factors — monitor proposals if heavily borrowed."],
    },
    "connext-bridge": {
        "short": "Modular bridge (Everclear) — fast cross-chain transfers через intent-based routing.",
        "long": "Connext (rebranding toward Everclear) — cross-chain interoperability using modular intent architecture for fast cheap transfers.",
        "tagline": "Intents cross chains — modular bridge Connext/Everclear.",
        "highlight": "Connext Bridge на bridge.connext.network enables cross-chain swaps и transfers with solver network filling intents. Evolved toward Everclear brand for clearing layer vision. Competitive with Across и Socket on speed. Technical architecture emphasizes modularity — integrations across growing chain set.",
        "facts": [
            "Connext → Everclear pivot 2024: rebrand reflected shift from bridge to clearing network narrative.",
            "Intent-based bridge 2024 hot trend — Connext early mover before Anoma и others mainstreamed term.",
            "Bridge sector consolidation: survivors differentiate on UX и solver liquidity, not just chain count.",
        ],
        "tips": ["Compare Connext quote with Bungee aggregation — may route through same solvers differently."],
        "warnings": ["Intent systems rely on solver honesty и liquidity — rare failures possible on exotic routes."],
    },
    "convex": {
        "short": "Curve booster — max CVX rewards и simplified Curve/Frax staking без lock complexity.",
        "long": "Convex Finance — deposits Curve LP tokens, maximizes CRV rewards, aggregates veCRV power. Dominates Curve gauge wars.",
        "tagline": "Curve yield на стероидах — veCRV power без lock.",
        "highlight": "Convexfinance.com locks more veCRV than anyone — LPs deposit Curve pool tokens, earn boosted CRV + CVX + fees without managing veCRV locks. Central to Curve ecosystem economics since 2021. vlCVX holders vote gauges и receive bribes. Frax и other integrations expanded scope. Smart contract battle-tested but Curve dependency means Curve risk = Convex risk.",
        "facts": [
            "Convex launch 2021: TVL $0 → $15B in months — most successful Curve meta-protocol ever.",
            "Gauge wars: protocols paid Convex voters millions in bribes — DeFi political economy thesis material.",
            "CRV price -90% hurt CVX holders harder — leveraged bet on Curve ecosystem revenue.",
        ],
        "tips": ["Understand you earn CRV, CVX и pool fees — diversify exit timing on three tokens."],
        "warnings": ["Convex is Curve wrapper — if Curve pool exploited, Convex LPs affected."],
    },
    "core-bridge-by-l0": {
        "short": "Official Core DAO bridge через LayerZero — BTC staking chain ↔ multichain assets.",
        "long": "Core Bridge (LayerZero) — cross-chain gateway for Core blockchain connecting BTC-aligned L1 with EVM ecosystems via LayerZero OFT.",
        "tagline": "Gateway Core chain — LayerZero мост для экосистемы Satoshi Plus.",
        "highlight": "Core DAO на bridge.coredao.org uses LayerZero for token transfers between Core и Ethereum, BSC и др. Core combines Bitcoin hash power и delegated staking — bridge links that ecosystem to broader DeFi. LayerZero speed with Core-native token support. Verify official bridge contract for CORE и wrapped assets.",
        "facts": [
            "Core launch 2023 with Satoshi Plus consensus — bridge essential for DeFi beyond native chain.",
            "LayerZero integration meant Core users farmed ZRO eligibility — bridge txs partly sybil-driven.",
            "BTC staking narrative 2024: Core positioned at intersection — bridge connects story to usable DeFi.",
        ],
        "tips": ["Confirm destination token contract on Core — wrapped assets have multiple versions historically."],
        "warnings": ["New L1 bridges — wait for audit maturity before life-changing sums."],
    },
    "cowswap": {
        "short": "MEV-protected DEX — batch auctions от CoW Protocol, traders не платят sandwich tax.",
        "long": "CowSwap (CoW Protocol) — DEX aggregating via batch auctions where solvers compete to fill orders at best price, MEV returned to users.",
        "tagline": "Торговля защищена от MEV — solvers конкурируют, surplus остаётся тебе.",
        "highlight": "Swap.cow.fi uses intent-based batch auctions: sign order, solver executes in batch with price improvement. MEV protection core value — no sandwich on your swap. Integrates Uniswap, Curve и др. as liquidity sources. Gasless orders possible via relayers. ETH mainnet primary venue; growing L2 support. Preferred whales и DAOs moving size on-chain.",
        "facts": [
            "CoW Protocol name from «Coincidence of Wants» — economic concept became MEV solution brand.",
            "Solver competition returned $100M+ MEV surplus to users cumulative — rare DeFi win for retail.",
            "Gnosis merged ecosystem alignment — CoW DAO governance independent but GNO family connections.",
        ],
        "tips": ["Use limit orders for non-urgent trades — solvers may wait for better batch price."],
        "warnings": ["Order expiry matters — unfilled orders need resign; don't assume instant fill."],
    },
    "crodex": {
        "short": "DEX на Cronos — swap и farm в Crypto.com ecosystem chain.",
        "long": "Crodex — AMM на Cronos chain (Crypto.com EVM) with swaps, liquidity pools и yield farms.",
        "tagline": "Нативный DEX Cronos — swap в экосистеме CRO.",
        "highlight": "Crodex.app обслуживает Cronos DeFi users — CRO pairs, ecosystem tokens, farm incentives. Cronos activity tied to Crypto.com marketing и CRO price cycles. Not deep global liquidity — functional for Cronos-native assets when you're already in chain via Crypto.com bridge.",
        "facts": [
            "Cronos launch 2021 with $500M marketing — Crodex among first DEXes riding CRO hype wave.",
            "CRO -90% from ATH drained Cronos DeFi TVL — Crodex quiet but operational.",
            "Crypto.com app integration drove users who never used MetaMask — different demographic than Ethereum DeFi.",
        ],
        "tips": ["Bridge CRO via official Crypto.com Cronos bridge — third-party routes add risk."],
        "warnings": ["Ecosystem chain concentration risk — Cronos activity follows CRO price и CEX marketing."],
    },
    "dao-maker": {
        "short": "Launchpad и incubator — SHO sales, strong holder offerings для retail early access.",
        "long": "DAO Maker — token launch platform with Strong Holder Offerings (SHO), staking tiers и venture incubator backing projects.",
        "tagline": "SHO launchpad — stake DAO, молись за allocation.",
        "highlight": "DAO Maker app.daomaker.com runs SHO sales: stake DAO token for allocation weight, participate in vetted project launches. Incubator track record includes notable names (mixed outcomes). KYC common. 2021 hack history — platform upgraded security since. Launchpad returns heavily skewed — few winners, many losers.",
        "facts": [
            "August 2021 hack: ~$7M stolen from user wallets via compromised widget — DAO Maker rebuilt trust slowly.",
            "SHO format copied across industry — DAO Maker's brand became verb for «staking for allocation».",
            "Top SHO winners (ORAO, etc.) created permanent FOMO — statistical survivors, not guaranteed formula.",
        ],
        "tips": ["Tier weight from DAO staking — calculate cost of capital vs expected allocation EV."],
        "warnings": ["Launchpad tokens often dump at unlock — don't stake life savings for lottery tickets."],
    },
    "debank": {
        "short": "DeFi portfolio tracker — все wallets и chains в одном dashboard с social feed.",
        "long": "DeBank — read-only portfolio aggregator across 100+ chains. Net worth, DeFi positions, swap interface и Web3 social layer.",
        "tagline": "Всё, что есть on-chain — один dashboard, все chain.",
        "highlight": "DeBank.com индексирует wallets across Ethereum, L2s, Solana, BSC и dozens more — unified net worth и protocol breakdown. DeFi swap и bridge integrated. Social feed («Web3 profile») shows on-chain activity publicly unless privacy adjusted. Essential research tool for whale watching и self-audit. Read-only by default — connects wallet only for tx signing when swapping.",
        "facts": [
            "DeBank became default «check that wallet» tool — influencers doxxed themselves via public profiles.",
            "Rank feature gamified net worth — crypto flex culture quantified in USD on leaderboard.",
            "DeBank swap aggregator volume significant — portfolio app became trading entry point organically.",
        ],
        "tips": ["Adjust privacy settings if you don't want full portfolio public on DeBank profile."],
        "warnings": ["Public profile exposes holdings — OPSEC risk for large wallets."],
    },
    "debridge": {
        "short": "Fast cross-chain bridge — swaps и transfers с DLN (DeBridge Liquidity Network) solver model.",
        "long": "deBridge — interoperability protocol for cross-chain swaps, messaging и DLN intent fulfillment across 20+ chains.",
        "tagline": "Cross-chain на скорости — DLN solvers исполняют intent.",
        "highlight": "deBridge.finance enables asset transfers и arbitrary message passing across EVM и Solana. DLN uses off-chain solvers with on-chain settlement — competitive speed vs Across. deBridge points campaign drove volume 2024. Growing integrations in wallets и dApps. Check supported asset list — not every token on every route.",
        "facts": [
            "deBridge points airdrop farming 2024: volume exploded — sybil debate followed every points program.",
            "Solana ↔ EVM through deBridge captured flow as Wormhole faced competition.",
            "Cross-chain messaging enables more than transfers — NFT и governance use cases expanding.",
        ],
        "tips": ["Compare deBridge fee/time with Bungee quote on same route — winner varies daily."],
        "warnings": ["Solver model trust assumptions — use official app for large cross-chain moves."],
    },
    "dedust": {
        "short": "Leading DEX на TON — swap и pools для Telegram/crypto native TON ecosystem.",
        "long": "DeDust.io — primary AMM на The Open Network (TON) with deep integration into Telegram Web3 ecosystem.",
        "tagline": "Главный swap TON — хаб ликвидности Telegram chain.",
        "highlight": "DeDust доминирует TON DEX volume post-Telegram crypto push: swap TON, jettons, LP pools. Native TON wallet integration smooth for Telegram users. Ecosystem growth tied to Telegram mini-apps и NOTcoin wave. Competes with Ston.fi for TON liquidity — check both for best price.",
        "facts": [
            "TON revival 2024 via Telegram: DeDust volume 100x as mini-app users discovered on-chain swap.",
            "NOT и meme jettons on TON — DeDust frontline for memecoin casino on Telegram chain.",
            "Dedust vs Ston.fi TON DEX war mirrors every L1 — incentives decide LP loyalty.",
        ],
        "tips": ["Use TON-native wallet (Tonkeeper) for best DeDust UX — MetaMask not applicable here."],
        "warnings": ["Meme jettons on TON mostly zero value — treat as speculation not investment."],
    },
    "defibox": {
        "short": "DeFi suite на EOS — swap, lending, stablecoin в одной экосистеме Antelope chain.",
        "long": "Defibox — comprehensive DeFi platform на EOS/Antelope: swap, USN stablecoin, lending и resource management.",
        "tagline": "EOS DeFi all-in-one — swap, lend, mint USN.",
        "highlight": "Defibox.io — DeFi hub экосистемы EOS, older than most L2 DeFi. Swap pools, USN algorithmic stablecoin, lending markets. Loyal EOS community product; tiny vs Ethereum but functional for EOS-native assets. Historical significance in early DeFi beyond ETH.",
        "facts": [
            "EOS DeFi peak 2020–2021: Defibox TVL in hundreds of millions when EOS price alive.",
            "USN stablecoin depeg scares tested Defibox — survived where Terra didn't, different mechanism.",
            "Block.one EOS abandonment hurt all ecosystem apps — Defibox persisted on community EOS forks.",
        ],
        "tips": ["Confirm which EOS fork/network Defibox deploys on — Antelope fragmentation continues."],
        "warnings": ["EOS ecosystem shrunk — liquidity и developer activity far below peak."],
    },
    "desyn": {
        "short": "Structured DeFi products — on-chain fund pools, LSD и yield strategies as vaults.",
        "long": "DeSyn Protocol — decentralized structured products platform for creating и investing in on-chain fund pools и yield strategies.",
        "tagline": "Structured products DeFi — pools со стратегией, не просто APY.",
        "highlight": "DeSyn.io lets managers create tokenized strategy pools — LSD combinations, yield aggregations, structured returns. Investors deposit into pools with transparent on-chain rules. Niche between raw farming и TradFi funds. Smart contract risk on custom strategies — read pool composition before entry.",
        "facts": [
            "Structured products in DeFi repeatedly attempted since 2020 — DeSyn among survivors in bear market.",
            "LSD boom 2023: DeSyn pools packaged stETH + rewards strategies — composability marketing.",
            "On-chain fund manager reputation unenforceable — past performance ≠ future, especially in crypto.",
        ],
        "tips": ["Read pool strategy contract и underlying assets — structured ≠ safe."],
        "warnings": ["Custom strategy pools carry manager и smart contract risk — no FDIC."],
    },
    "dexguru": {
        "short": "DEX analytics aggregator — charts, pool data и trading interface across chains.",
        "long": "DexGuru (dex.guru) — analytics и trading front-end aggregating DEX data, charts и swap execution multi-chain.",
        "tagline": "Chart, analyze, swap — DEX terminal с data layer.",
        "highlight": "Dex.guru combines TradingView-style charts for on-chain pairs with aggregated swap execution. Track new pools, liquidity changes и whale trades. Power user tool for DEX traders who want data + execution without leaving tab. Supported chains include Ethereum, BSC, Polygon и more. Guru Network token for ecosystem incentives.",
        "facts": [
            "DexGuru rose as Dextools competitor — cleaner UI won segment of active DEX traders.",
            "New pool alerts saved degens и created bag holders — speed to ape unchanged outcome variance.",
            "Aggregator analytics + swap: data moat harder than execution — DexGuru bet on both.",
        ],
        "tips": ["Verify contract address on chart matches token you intend to buy — scam pairs clone names."],
        "warnings": ["Charts show price, not legitimacy — rug tokens chart beautifully until they don't."],
    },
}
