"""Russian content for WEB3_BATCH_4 — 50 slugs, kgen through nodepay."""

ENTRIES: dict[str, dict] = {
    "kgen": {
        "short": "Игровая Web3-платформа с квестами и on-chain наградами — когда геймплей и крипто-экономика связаны в одном приложении.",
        "long": "KGeN (kgen.io) объединяет игровые активности, квесты и токенизированные награды для сообщества геймеров. Платформа ориентирована на вовлечение через play-to-earn механики и партнёрства с игровыми студиями.",
        "tagline": "Квесты, награды и on-chain прогресс в играх.",
        "highlight": "KGeN строит мост между casual gaming и Web3: пользователи выполняют задания, участвуют в ивентах и получают on-chain rewards. Экосистема растёт через интеграции с играми и NFT-коллекциями. Для геймеров, которые хотят монетизировать время в игре без полного погружения в DeFi. Следи за условиями квестов и сроками claim — типичная модель «активность → поинты → токен».",
        "facts": [
            "Gaming × Web3 2024–2025: платформы вроде KGeN конкурировали за retention после краха P2E — выжили те, кто сделал награды вторичными, а не основным доходом.",
            "Партнёрские квесты с game studios часто дают ранний доступ к NFT или whitelist — фермеры гоняют multi-account, команды борются с sybil.",
            "On-chain rewards без sticky gameplay: классический паттерн «фарм ивента → дамп токена → пустая платформа» повторяется у большинства gaming hubs.",
        ],
        "tips": ["Читай правила квеста до старта — часть наград требует минимального on-chain баланса или KYC-партнёра."],
        "warnings": ["Игровые токены и NFT-награды волатильны — не считай их гарантированным доходом."],
    },
    "kiichain": {
        "short": "Тестнет KiiChain — экспериментальная L1 для ранних пользователей и разработчиков, которые хотят протестировать сеть до mainnet.",
        "long": "KiiChain (kiichain.io) — блокчейн-проект в стадии testnet. Пользователи подключают кошельки, выполняют транзакции и участвуют в ранних программах для будущего mainnet.",
        "tagline": "Ранний доступ к новой L1 через testnet.",
        "highlight": "Тестнет KiiChain на kiichain.io — точка входа для ранних пользователей: faucet, базовые транзакции, возможные квесты от команды. Типичный сценарий для новых L1 — накопление on-chain активности перед потенциальным airdrop. Gas бесплатный или из faucet, но время и внимание — реальная цена. Проверяй официальные каналы, не клоны testnet UI.",
        "facts": [
            "Testnet-сезон 2024–2025: десятки новых L1 конкурировали за «100k wallets» — KiiChain в той же волне охоты за ранней активностью.",
            "Faucet abuse: боты выжимают testnet tokens за минуты — команды вводят captcha, GitHub auth и rate limits.",
            "Testnet ≠ mainnet: контракты, адреса и токены могут полностью измениться перед запуском — не храни ценность on-chain.",
        ],
        "tips": ["Веди отдельный кошелёк для testnet — не смешивай с mainnet seed phrase на сомнительных сайтах."],
        "warnings": ["Фишинг testnet-сайтов распространён — всегда проверяй URL на официальном Twitter/Discord проекта."],
    },
    "kintsu": {
        "short": "Liquid staking на Monad и смежных сетях — стейкай нативный токен и получай LST для DeFi без разблокировки.",
        "long": "Kintsu (kintsu.xyz/staking) — протокол liquid staking: депозит MON или других поддерживаемых активов, получение receipt-токена для yield и composability в DeFi.",
        "tagline": "Стейк без заморозки ликвидности.",
        "highlight": "Kintsu позволяет стейкать в экосистеме Monad без потери ликвидности: LST можно использовать в lending, LP и других протоколах. Модель знакома по Lido и Rocket Pool, но на молодой chain с повышенными рисками smart contract и slashing. APR зависит от network rewards и комиссии протокола. Для тех, кто уже держит MON и хочет compound без ручного restaking.",
        "facts": [
            "Liquid staking на pre-mainnet chains: Kintsu и аналоги запускаются до полной зрелости сети — ранние LST часто торгуются с дисконтом к номиналу.",
            "Monad hype 2024–2025: staking-провайдеры конкурировали за первый billion TVL — marketing APR выше, чем sustainable yield после TGE.",
            "Slashing на молодых сетях ещё не battle-tested — LST premium = компенсация за tail risk, который розница недооценивает.",
        ],
        "tips": ["Сравни exchange rate LST с 1:1 — persistent depeg сигнализирует о проблемах ликвидности или доверии."],
        "warnings": ["Smart contract риск на новой chain выше, чем у Lido на Ethereum — не стейкай весь капитал в один протокол."],
    },
    "kuru": {
        "short": "DEX на emerging L2 — свапы и ликвидность для локальных пар, когда нужна нативная торговая площадка в экосистеме.",
        "long": "Kuru (kuru.io) — децентрализованная биржа в Web3-экосистеме с AMM или order book моделью. Точка входа для свапов и LP на поддерживаемых сетях.",
        "tagline": "Локальная ликвидность для своей chain.",
        "highlight": "Kuru.io — DEX для пользователей, которые уже в целевой сети и не хотят мостить активы ради свапа. Объёмы обычно скромнее топовых агрегаторов, зато для нативных токенов экосистемы это часто основная площадка. Следи за slippage на тонких парах и audit status контрактов. Типичный early-stage DEX с emissions-driven TVL.",
        "facts": [
            "Micro-DEX на новых L2: первые недели TVL растёт на incentives, потом падает на 80% — Kuru в типичном цикле «launch → farm → exit».",
            "Конкуренция с агрегаторами: Jupiter и 1inch забирают flow, локальные DEX живут на экзотических парах и pre-listing токенах.",
            "Phishing-клоны DEX UI — классика: один символ в домене, и пользователь approve'ит malicious контракт.",
        ],
        "tips": ["Проверяй price impact перед крупным свапом — глубина пула на новых DEX часто минимальна."],
        "warnings": ["Неаудированные контракты и низкая ликвидность — комбо для потери средств на IL и rug."],
    },
    "lagrange": {
        "short": "ZK coprocessor и инфраструктура доказательств — verifiable compute off-chain с on-chain verification для DeFi и cross-chain.",
        "long": "Lagrange (lagrange.dev) строит ZK-инфраструктуру: coprocessors для тяжёлых вычислений, которые верифицируются on-chain. Используется протоколами для pricing, indexing и proof-based interoperability.",
        "tagline": "ZK coprocessor с on-chain proof.",
        "highlight": "Lagrange — инфраструктурный слой ZK era: вместо дорогих on-chain вычислений протоколы делегируют расчёты coprocessor и получают succinct proof. Применения — DeFi pricing, cross-chain state, verifiable analytics. Для разработчиков и power users, интегрирующих ZK в dApps. Не consumer app — dev tooling и B2B infra с потенциальным token/nodes layer для early participants.",
        "facts": [
            "ZK coprocessor meta 2024: Lagrange конкурировала с Risc Zero и SP1 за «default proof layer» — победит интеграция, не TPS на landing page.",
            "Succinct и Lagrange пересекаются в ZK infra space — инвесторы и devrel активно переключают внимание между проектами каждый квартал.",
            "Proof generation time vs cost: coprocessor экономит gas, но добавляет latency — не каждый DeFi flow готов ждать секунды на proof.",
        ],
        "tips": ["Если участвуешь в dev/testnet программе — документируй on-chain proof submissions для potential retroactive rewards."],
        "warnings": ["ZK infra проекты долго без consumer product — «ранняя активность» может не конвертироваться в airdrop."],
    },
    "layeredge": {
        "short": "Edge computing L2 — децентрализованная инфраструктура на границе сети для Web3-приложений с низкой задержкой.",
        "long": "LayerEdge (layeredge.io) — проект на стыке edge computing и blockchain: распределённые ноды ближе к пользователю для быстрого исполнения и verifiable workloads.",
        "tagline": "Edge compute для Web3-инфраструктуры.",
        "highlight": "LayerEdge позиционируется как infra для приложений, которым нужна скорость edge и гарантии blockchain. Модель может включать node operators, staking и task marketplace. Early stage — testnet, квесты, onboarding разработчиков. Для тех, кто фармит infra-narrative (DePIN, edge, ZK) параллельно с L2 meta. Следи за официальными анонсами tokenomics.",
        "facts": [
            "DePIN + edge 2024–2025: LayerEdge в одном кластере с io.net и аналогами — «запусти ноду, получи поинты» стало стандартным GTM.",
            "Обещания edge latency часто тестируются только в demo — production load на distributed nodes другая история.",
            "Infra airdrop hunters запускают VPS farms — команды ужесточают hardware attestation и geo requirements.",
        ],
        "tips": ["Для node programs читай minimum specs — undersized VPS не засчитывается в rewards."],
        "warnings": ["Запуск ноды на непроверенном софте — риск для сервера; используй изолированную VM."],
    },
    "layerhub": {
        "short": "Агрегатор протоколов и аналитика — hub для Polymarket и смежных prediction/DeFi инструментов в одном интерфейсе.",
        "long": "LayerHub (layerhub.xyz) — навигационный слой и analytics hub для Web3-протоколов, включая Polymarket и другие markets. Упрощает discovery и мониторинг позиций.",
        "tagline": "Один вход в протоколы и prediction markets.",
        "highlight": "LayerHub агрегирует ссылки, метрики и контекст вокруг популярных Web3-протоколов — особенно prediction markets вроде Polymarket. Не замена нативному UI, а overlay для трейдеров и researchers. Полезен для сравнения markets, tracking exposure и быстрого перехода в нужный протокол. Проверяй, что outbound links ведут на официальные домены, не referral-клоны.",
        "facts": [
            "Prediction market boom 2024: агрегаторы вроде LayerHub выросли на трафике «куда ставить на выборы» — SEO и crypto Twitter дали organic growth.",
            "Hub-сайты часто не custody funds — ценность в curation; outdated links после rebrand протокола — типичная боль пользователей.",
            "Polymarket доминировал narrative — LayerHub и аналоги конкурировали за «default bookmark» у political bettors.",
        ],
        "tips": ["Перед ставкой на prediction market всё равно сверяй resolution rules на официальном сайте протокола."],
        "warnings": ["Агрегатор не гарантирует актуальность контрактов — всегда проверяй URL и market ID on-chain."],
    },
    "linera": {
        "short": "Blockchain с microchains — параллельные цепочки приложений для масштабирования без классического sharding UX.",
        "long": "Linera (portal.linera.net) — L1 с архитектурой microchains: каждое приложение может иметь свою chain с общей security. Testnet и developer portal для ранних билдеров.",
        "tagline": "Масштаб через параллельные app-chains.",
        "highlight": "Linera предлагает модель, где dApps получают dedicated microchain вместо конкуренции за block space одной monolithic chain. Portal.linera.net — вход для wallet, faucet и dev tools. Для разработчиков Rust/Wasm и пользователей testnet-квестов. Нарратив — масштаб web2 с гарантиями web3. Early stage: активность on-chain может учитываться в future rewards programs.",
        "facts": [
            "Microchain narrative 2023–2024: Linera привлекла внимание после публикаций ex-Meta researchers — academic pedigree ≠ mainnet traction.",
            "Testnet wallet downloads скачками коррелируют с airdrop rumors — реальная dev activity измеряется commits, не tx count.",
            "Конкуренция с Aptos/Sui Move chains — Linera выбирает Wasm path, другой developer stack, та же битва за builders.",
        ],
        "tips": ["Для dev grant programs готовь working demo на testnet — tx farming без кода реже конвертируется в allocation."],
        "warnings": ["Testnet tokens не имеют ценности — не покупай «Linera accounts» у перекупщиков."],
    },
    "linktr": {
        "short": "Официальный Linktree Succinct Labs — все ссылки на ZK infra, testnet и socials в одном месте.",
        "long": "Linktr (linktr.ee/succinctlabs) — агрегированная страница ссылок Succinct Labs, команды за SP1 и ZK proof infrastructure. Точка входа в документацию, Discord и программы.",
        "tagline": "Один клик до ZK infra и community Succinct Labs.",
        "highlight": "Succinct Labs — один из ключевых игроков ZK VM (SP1) и proof generation stack. Их Linktree собирает официальные ресурсы: GitHub, docs, testnet, careers. Для ZK-native developers и airdrop hunters, следящих за proof infrastructure meta. Не dApp — navigation hub. Всегда сверяй, что переходишь с linktr.ee/succinctlabs, а не с typosquatting clone.",
        "facts": [
            "Succinct SP1 launch 2024: «prove anything in Rust» стало мемом среди ZK devs — Linktree traffic взлетел в launch week.",
            "ZK infra funding 2024–2025: Succinct подняла significant round — конкуренция с Risc Zero за default zkVM heated up.",
            "Linktree как official link hub — стандарт для crypto teams после ban waves в social; один broken link = тысячи confused users.",
        ],
        "tips": ["Bookmark официальный Linktree — в ZK space много fake Discord invites в Google Ads."],
        "warnings": ["Не вводи seed phrase на сайтах, на которые попал через неофициальные Linktree-клоны."],
    },
    "litvm": {
        "short": "LitVM — EVM-совместимая среда на Lit Protocol для программируемых ключей и verifiable Web3 actions.",
        "long": "LitVM (litvm.com) развивает EVM execution layer в экосистеме Lit Protocol: smart contracts + MPC/TEE keys для условного signing и automation.",
        "tagline": "EVM на Lit Protocol с programmable keys.",
        "highlight": "Lit Protocol известен PKP (programmable key pairs) и decentralized signing. LitVM расширяет story до полноценного EVM runtime для dApps, которым нужны automated on-chain actions с distributed key management. Use cases — AI agents, limit orders, account abstraction patterns. Для developers и early node operators в Lit ecosystem. Следи за testnet milestones и integration docs.",
        "facts": [
            "Lit Protocol pivoted от «NFT licensing» к core infra для signing — LitVM часть этой эволюции 2023–2025.",
            "MPC + EVM combo редкость: security audits здесь critical — один bug в key material = total loss.",
            "Agent economy hype 2025: LitVM позиционируется под AI agents with on-chain wallets — narrative ahead of product-market fit.",
        ],
        "tips": ["При интеграции PKP читай scope permissions — over-permissive Lit Actions = attack surface."],
        "warnings": ["Programmable keys ≠ custodial recovery — потеря access conditions может навсегда заблокировать assets."],
    },
    "logx": {
        "short": "Perpetual DEX — торговля фьючерсами on-chain с leverage на поддерживаемых L2 и alt-L1.",
        "long": "LogX (app.logx.network) — децентрализованная биржа perpetual contracts: long/short с leverage, funding rates, on-chain settlement без CEX custody.",
        "tagline": "Leverage on-chain без KYC-биржи.",
        "highlight": "LogX.network конкурирует в переполненном perp DEX секторе: GMX, dYdX, Hyperliquid и десятки клонов. Преимущество — deployment на emerging chains с incentives для early traders. Funding, liquidation и oracle risk — стандартный набор perp risks. Для опытных трейдеров, не для «first crypto buy». Проверяй open interest, depth и audit перед крупными позициями.",
        "facts": [
            "Perp DEX wars 2024: новые chains платят traders rebates за volume — wash trading раздувает метрики на половине perp venues.",
            "LogX и аналоги на L2 часто запускаются до mature oracle infra — flash crash liquidation cascades случались на multiple perp DEX.",
            "Points season на perps: professional MM dominate leaderboard — retail farms funding fees net negative.",
        ],
        "tips": ["Начни с малого leverage на новой perp DEX — liquidation engine и mark price могут отличаться от CEX."],
        "warnings": ["Perpetual contracts с высоким leverage могут ликвидировать позицию за минуты — используй stop-loss on-chain где доступно."],
    },
}
